### ISSUE TITLE
select and integrate a scripting language

### ISSUE THREAD

**Issue by mgerhold** [mgerhold/silly-sprites#10]

**Comment by kgnet88** [comment]
To embed Python into C++:

- Python Embedding: https://docs.python.org/3/extending/embedding.html
- Building Python statically: https://wiki.python.org/moin/BuildStatically
- Embedding Python on Windows(why does it have to be a dll): https://stackoverflow.com/questions/3953039/embedding-python-on-windows-why-does-it-have-to-be-a-dll
-

**Comment by mgerhold** [comment]
I stumbled upon [AngelScript](https://www.angelcode.com/angelscript/) and would like to also take that into considerations here.

**Comment by mgerhold** [comment]
The first step of integration has been done, see #57
