### ISSUE TITLE
implement OpenGL abstraction layer

### ISSUE THREAD

**Issue by mgerhold** [mgerhold/silly-sprites#5]

**Comment by kgnet88** [comment]
If I have questions about your implementation, where can I ask them? Only during the stream, here in the issues or do you plan to open the discussion?

**Comment by mgerhold** [comment]
> If I have questions about your implementation, where can I ask them? Only during the stream, here in the issues or do you plan to open the discussion?

I activated the "discussions" section on this repo. Feel free to open a thread there 🙂
